### ISSUE TITLE
Fatal error when installing aracon

### ISSUE THREAD

**Issue by shilaixing** [isovic/aracon#1]
Hello! 
 I tried to install aracon on my Linux service (CentOS release 6.2) with following steps：
1) git clone https://github.com/isovic/aracon.git
2) cd aracon
3) make

The installing process was stoped with the following messages:
[GET MODULES] 
Submodule 'components/graphmap' () registered for path 'components/graphmap'
Submodule 'components/miniasm' () registered for path 'components/miniasm'
Submodule 'components/racon' () registered for path 'components/racon'
Submodule 'components/samscripts' () registered for path 'components/samscripts'
Submodule path 'components/graphmap': checked out '1d16f07888b60547094e8257688088d6f00be8af'
Submodule 'codebase/argumentparser' (https://github.com/isovic/graphmap.git) registered for path 'codebase/argumentparser'
Submodule 'codebase/seqlib' (https://github.com/isovic/graphmap.git) registered for path 'codebase/seqlib'
Submodule path 'codebase/argumentparser': checked out 'd0dae52c3d1b029f65f3bf4f0cd671e88dbeb98f'
Submodule path 'codebase/seqlib': checked out 'e0833dc91343ac7a1e33fb6b2f08bc9009bf9a8b'
Submodule path 'components/racon': checked out '0bb2fd6ca9fa4492b0ba7b6751d242795c02f6fa'
Submodule 'codebase/argparser' (https://github.com/isovic/racon.git) registered for path 'codebase/argparser'
Submodule 'codebase/samscripts' (https://github.com/isovic/racon.git) registered for path 'codebase/samscripts'
Submodule 'codebase/seqlib' (https://github.com/isovic/racon.git) registered for path 'codebase/seqlib'
Submodule 'codebase/spoa' (https://github.com/isovic/racon.git) registered for path 'codebase/spoa'
Submodule path 'components/samscripts': checked out 'b40d0663f6a5c477d5f6908f83567758fb627e08'
Entering 'components/graphmap'
From https://github.com/isovic/graphmap
 * branch            master     -> FETCH_HEAD
Updating 1d16f07..817ba03
Fast-forward
 Makefile                         |    2 +-
 README.md                        |    6 +-
 codebase/argumentparser          |    2 +-
 codebase/seqlib                  |    2 +-
 doc/changelog.md                 |    6 ++
 src/alignment/anchored.cc        |    2 +-
 src/alignment/cigargen.cc        |  146 +++++++++++++++++++++++++++-----------
 src/alignment/cigargen.h         |   20 ++++++
 src/graphmap/graphmap.cc         |    6 +-
 src/graphmap/graphmap.h          |    7 ++
 src/graphmap/process_read.cc     |    2 +-
 src/graphmap/region_selection.cc |   19 +++--
 src/index/index.h                |   67 +----------------
 src/index/index_hash.cc          |   10 ++-
 src/program_parameters.cc        |    9 +--
 src/program_parameters.h         |    3 +-
 16 files changed, 176 insertions(+), 133 deletions(-)
Entering 'components/miniasm'
From https://github.com/lh3/miniasm
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Entering 'components/racon'
From https://github.com/isovic/racon
 * branch            master     -> FETCH_HEAD
Updating 0bb2fd6..bd1a7c1
Fast-forward
 .gitignore                                         |    1 +
 Makefile                                           |    3 +-
 README.md                                          |   65 ++++-
 codebase/argparser                                 |    2 +-
 codebase/samscripts                                |    2 +-
 codebase/seqlib                                    |    2 +-
 example1-lambda.sh                                 |   56 ----
 example11-erc-ecoli_map006.sh                      |  155 -----------
 ...ple12-paf-lambda.sh => example1_1-paf-lambda.sh |    5 +-
 ...le7-mhap-lambda.sh => example1_2-mhap-lambda.sh |    6 +-
 ...hap-ecoli_map006.sh => example1_3-sam-lambda.sh |   53 ++--
 example2-paf-pipe-lambda.sh                        |  102 +++++++
 example10-erc-lambda.sh => example3-erc-lambda.sh  |    7 +-
 example8_1-mhap-ecoli_map006-1111.sh               |  122 --------
 example8_2-mhap-ecoli_map006-pileup.sh             |  122 --------
 example9-mhap-ecoli_pacbio_160x.sh                 |  122 --------
 example9_1-mhap-ecoli_pacbio_160x-1111.sh          |  122 --------
 run-measure.sh                                     |   13 -
 scripts/edcontigs.py                               |    2 +-
 scripts/evalcontigs.py                             |    2 +-
 scripts/intervaltree.py                            |    2 +-
 scripts/lis.py                                     |    2 +-
 src/consensus/consensus.cc                         |  195 ++++++++++++-
 src/consensus/consensus.h                          |    6 +-
 src/consensus/pileup.cc                            |    2 +-
 src/consensus/pileup.h                             |    2 +-
 src/main.cc                                        |  205 ++++++++------
 src/mhap.cc                                        |  290 +++++++++++++-------
 src/mhap.h                                         |   20 +-
 29 files changed, 727 insertions(+), 961 deletions(-)
 delete mode 100755 example1-lambda.sh
 delete mode 100755 example11-erc-ecoli_map006.sh
 rename example12-paf-lambda.sh => example1_1-paf-lambda.sh (98%)
 rename example7-mhap-lambda.sh => example1_2-mhap-lambda.sh (95%)
 rename example8-mhap-ecoli_map006.sh => example1_3-sam-lambda.sh (74%)
 create mode 100755 example2-paf-pipe-lambda.sh
 rename example10-erc-lambda.sh => example3-erc-lambda.sh (95%)
 delete mode 100755 example8_1-mhap-ecoli_map006-1111.sh
 delete mode 100755 example8_2-mhap-ecoli_map006-pileup.sh
 delete mode 100755 example9-mhap-ecoli_pacbio_160x.sh
 delete mode 100755 example9_1-mhap-ecoli_pacbio_160x-1111.sh
 delete mode 100755 run-measure.sh
Entering 'components/samscripts'
From https://github.com/isovic/samscripts
 * branch            master     -> FETCH_HEAD
Updating b40d066..8225661
Fast-forward
 src/alignmentstats.py     |    2 +-
 src/apply-consensus.py    |    2 +-
 src/consensus.py          |    2 +-
 src/count_mapped_reads.py |    2 +-
 src/errorrates.py         |    2 +-
 src/fastqfilter.py        |    4 +-
 src/fastqparser.py        |    2 +-
 src/samfilter.py          |    2 +-
 src/svconsensus.py        |    2 +-
 src/utility_sam.py        |  515 ++++++++++++++++++++++++++++++++-------------
 src/vcffilter.py          |    2 +-
 src/venn_of_sams.py       |    2 +-
 12 files changed, 385 insertions(+), 154 deletions(-)
[GraphMap] components/graphmap/bin/Linux-x64/graphmap
cd components/graphmap; make modules && make -j 4
make[1]: Entering directory `/share/work2/staff/xingsk/software_install/Minisam_Racon/aracon/components/graphmap'
git submodule update --init --recursive
Submodule 'codebase/argumentparser' () registered for path 'codebase/argumentparser'
Submodule 'codebase/seqlib' () registered for path 'codebase/seqlib'
Submodule path 'codebase/argumentparser': checked out '72af9764acefbcc92ff76e3aba8a83d9a3e33671'
Submodule path 'codebase/seqlib': checked out '129d39a97ba56863bea98d3125f4241b26f36341'
git submodule foreach git pull origin master
Entering 'codebase/argumentparser'
From https://github.com/isovic/argumentparser
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Entering 'codebase/seqlib'
From https://github.com/isovic/seqlib
 * branch            master     -> FETCH_HEAD
Updating 129d39a..a93e7d9
Fast-forward
 src/utility/utility_general.cc |    8 ++++++--
 src/utility/utility_general.h  |    3 ++-
 2 files changed, 8 insertions(+), 3 deletions(-)
make[1]: Leaving directory `/share/work2/staff/xingsk/software_install/Minisam_Racon/aracon/components/graphmap'
make[1]: Entering directory `/share/work2/staff/xingsk/software_install/Minisam_Racon/aracon/components/graphmap'
Makefile:97: "*** WARNING g++ minor version <7 ***"
mkdir -p obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.o codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp
mkdir -p obj_linux/codebase/seqlib/src/libs/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/codebase/seqlib/src/libs/edlib.o codebase/seqlib/src/libs/edlib.cpp
mkdir -p obj_linux/codebase/seqlib/src/libs/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/codebase/seqlib/src/libs/opal.o codebase/seqlib/src/libs/opal.cpp
mkdir -p obj_linux/codebase/argumentparser/src/
**codebase/seqlib/src/libs/edlib.cpp:4:19: Fatal error: cstdlib：No such file or directory**
compilation terminated
make[1]: *** [obj_linux/codebase/seqlib/src/libs/edlib.o] error 1
make[1]: *** waiting for unfinished jobs....
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/codebase/argumentparser/src/argparser.o codebase/argumentparser/src/argparser.cc
In file included from codebase/argumentparser/src/argparser.cc:10:0:
**codebase/argumentparser/src/argparser.h:16:18: Fatal error：string：No such file or directory**
compilation terminated
make[1]: *** [obj_linux/codebase/argumentparser/src/argparser.o] error 1
make[1]: *** No child processes. Stop.
make: *** [components/graphmap/bin/Linux-x64/graphmap] error 2

So what can i do now?

**Comment by isovic** [comment]
Hi,
Strange that the compiler cannot find the STL string header - which compiler (and version) are you using to make the project?

Best regards,
Ivan.

**Comment by shilaixing** [comment]
The compiler version was gcc_5.4.0 (gcc >= 4.8). You remind me of the version, so I try another version(gcc_4.9.1). The good news is it works! Thank you very much!

**Comment by isovic** [comment]
Great, thanks!
I need to inspect this in detail.

Best regards,
Ivan.
